language: python
cache: pip
dist: xenial

python:
    - 3.7
    - 3.8
    - nightly
install: pip install -e .
script: python setup.py test

matrix:
    fast_finish: true
    allow_failures:
        - python: "latest"

