name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install project
      run: |
        python -m pip install -e ".[dev]"
    - name: Build and publish
      env:
        FLIT_USERNAME: "__token__"
        FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m flit publish
